### ISSUE TITLE
Example-app not working

### ISSUE THREAD

**Issue by edebu** [SoftwareBrothers/adminjs-leaflet#4]
Hello, I try to run example-app from https://docs.adminjs.co/basics/features/leaflet-maps#example and I got the following error:

D:\Projects\adminjs-leaflet\example-app\node_modules\rollup\dist\shared\rollup.js:198
        base = Object.assign(new Error(base.message), base);
                             ^
Error: 'default' is not exported by node_modules/@adminjs/leaflet/lib/components/LeafletSingleMarkerMap.jsx, imported by .adminjs/.entry.js
    at error (D:\Projects\adminjs-leaflet\example-app\node_modules\rollup\dist\shared\rollup.js:198:30)
    at Module.error (D:\Projects\adminjs-leaflet\example-app\node_modules\rollup\dist\shared\rollup.js:12560:16)
    at Module.traceVariable (D:\Projects\adminjs-leaflet\example-app\node_modules\rollup\dist\shared\rollup.js:12919:29)
    at ModuleScope.findVariable (D:\Projects\adminjs-leaflet\example-app\node_modules\rollup\dist\shared\rollup.js:11571:39)
    at Identifier.bind (D:\Projects\adminjs-leaflet\example-app\node_modules\rollup\dist\shared\rollup.js:7570:40)
    at AssignmentExpression.bind (D:\Projects\adminjs-leaflet\example-app\node_modules\rollup\dist\shared\rollup.js:5400:23)
    at ExpressionStatement.bind (D:\Projects\adminjs-leaflet\example-app\node_modules\rollup\dist\shared\rollup.js:5400:23)
    at Program.bind (D:\Projects\adminjs-leaflet\example-app\node_modules\rollup\dist\shared\rollup.js:5396:73)
    at Module.bindReferences (D:\Projects\adminjs-leaflet\example-app\node_modules\rollup\dist\shared\rollup.js:12556:18)
    at Graph.sortModules (D:\Projects\adminjs-leaflet\example-app\node_modules\rollup\dist\shared\rollup.js:23193:20)
    at Graph.build (D:\Projects\adminjs-leaflet\example-app\node_modules\rollup\dist\shared\rollup.js:23071:14)
    at async D:\Projects\adminjs-leaflet\example-app\node_modules\rollup\dist\shared\rollup.js:23768:13
    at async catchUnfinishedHookActions (D:\Projects\adminjs-leaflet\example-app\node_modules\rollup\dist\shared\rollup.js:23247:20)
    at async rollupInternal (D:\Projects\adminjs-leaflet\example-app\node_modules\rollup\dist\shared\rollup.js:23765:5)
    at async build (D:\Projects\adminjs-leaflet\example-app\node_modules\adminjs\lib\backend\bundler\bundler.js:51:20)
    at async build (D:\Projects\adminjs-leaflet\example-app\node_modules\adminjs\lib\backend\bundler\user-components-bundler.js:68:18) {
  code: 'MISSING_EXPORT',
  url: 'https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module',
  id: 'D:\\Projects\\adminjs-leaflet\\example-app\\.adminjs\\.entry.js',
  pos: 36,
  loc: {
    column: 7,
    file: 'D:\\Projects\\adminjs-leaflet\\example-app\\.adminjs\\.entry.js',
    line: 2
  },
  frame: '1: AdminJS.UserComponents = {}\n' +
    "2: import LeafletSingleMarkerMap from '../node_modules/@adminjs/leaflet/lib/components/LeafletSingleMarkerMap'\n" +
    '          ^\n' +
    '3: AdminJS.UserComponents.LeafletSingleMarkerMap = LeafletSingleMarkerMap\n' +
    "4: import LeafletSingleMarkerMapPropertyComponent from '../node_modules/@adminjs/leaflet/lib/components/LeafletSingleMarkerMapPropertyComponent'",
  watchFiles: [
    'D:\\Projects\\adminjs-leaflet\\example-app\\.adminjs\\.entry.js',
    'D:\\Projects\\adminjs-leaflet\\example-app\\node_modules\\@adminjs\\leaflet\\lib\\components\\LeafletSingleMarkerMapPropertyComponent.jsx',
    'D:\\Projects\\adminjs-leaflet\\example-app\\node_modules\\@adminjs\\leaflet\\lib\\components\\LeafletSingleMarkerMap.jsx',
    'D:\\Projects\\adminjs-leaflet\\example-app\\node_modules\\@adminjs\\leaflet\\lib\\components\\LeafletMultipleMarkersMapPropertyComponent.jsx',
    'D:\\Projects\\adminjs-leaflet\\example-app\\node_modules\\@adminjs\\leaflet\\lib\\components\\LeafletMultipleMarkersMap.jsx',
    '\x00rollupPluginBabelHelpers.js'
  ]
}
error Command failed with exit code 1.

I'll be happy if you can help me

**Comment by dziraf** [comment]
@edebu I think the documentation is missing the part where you have to install and build the library in `adminjs-leaflet` folder first since the example app uses the source version instead of the version from NPM registry.

Instead of:
```
$ cd adminjs-leaflet/example-app
```
Do:
```
$ cd adminjs-leaflet
$ yarn && yarn build
$ cd example-app
```
